import { ComparisonPageData } from '../types';

export const COMPARISONS: ComparisonPageData[] = [
  {
    slug: 'bpo-vs-internal-team',
    title: 'BPO vs. Building an Internal Operations Team',
    subtitle: 'Outsourcing a function and hiring an in-house team both work. The right call depends on speed, management bandwidth, and how core the function is to your product.',
    optionA: {
      name: 'TrivianEdge BPO',
      summary: 'A managed offshore team runs the function for you: TrivianEdge handles sourcing, employment, and day-to-day HR, while you keep control of the work itself.',
      goodFor: ['Support functions you need running well but don\'t want to manage', 'Getting a function live in around 30 days instead of a multi-month hiring cycle', 'Scaling headcount up or down without renegotiating contracts each time'],
      tradeoffs: ['You are not building in-house institutional ownership of the function', 'Works best when the function has clear processes to hand off, not deep tacit knowledge held by one person'],
    },
    optionB: {
      name: 'Internal operations team',
      summary: 'You hire, manage, and grow the function directly: full control, but you also carry the full cost and time of building the management layer around it.',
      goodFor: ['Functions that are core to your competitive advantage and need deep, permanent ownership', 'Teams where daily real-time collaboration with almost no timezone overlap is required'],
      tradeoffs: ['Hiring, onboarding, and building management infrastructure typically takes months, not weeks', 'You absorb the full employer overhead (benefits, payroll admin, HR, compliance) on top of salary'],
    },
    rows: [
      { factor: 'Time to a working team', a: 'Around 30 days, TrivianEdge\'s typical deployment time', b: 'Typically several months once sourcing, interviewing, and onboarding are accounted for' },
      { factor: 'Who manages HR and compliance', a: 'TrivianEdge, via in-country EOR and payroll partners', b: 'You, directly: payroll, benefits, and local employment law become your responsibility' },
      { factor: 'Cost structure', a: 'One line item covering the team and its management overhead', b: 'Salary plus benefits, payroll taxes, office/equipment, and HR/legal time: usually adds 20-40% on top of salary alone' },
      { factor: 'Flexibility to scale', a: 'Scale up or down without renegotiating employment contracts', b: 'Headcount changes mean hiring or layoffs, each with its own cost and time' },
      { factor: 'Best fit', a: 'Support functions: back-office, customer support, finance ops, admin', b: 'Functions that are core to your product or competitive moat' },
    ],
    verdict: 'If the function needs to exist and run well, but isn\'t the reason customers choose you, a managed BPO team is usually faster and cheaper than building the management layer from scratch. If the function is core to your product or requires constant real-time collaboration, an internal team earns its cost. Many TrivianEdge clients run both: a lean internal team on the strategic work, a BPO team on the operational load.',
    faqs: [
      { question: 'Can I start with BPO and bring the function in-house later?', answer: 'Yes. Some clients use TrivianEdge BPO to prove out a function\'s process and volume, then transition it to a direct hire or internal team once it\'s core enough to justify the investment. We build with clean handoffs in mind, not lock-in.' },
      { question: 'Does BPO mean I lose visibility into the work?', answer: 'No. You control the work: your BPO team follows your processes and reports to your managers. TrivianEdge manages HR, performance, and admin in the background, not the work itself.' },
      { question: 'How is cost actually compared between the two?', answer: 'Run your own roles and headcount through our savings calculator rather than relying on a flat industry percentage: the real gap depends on role, location, and how much management overhead you\'d otherwise be building.' },
    ],
    relatedServiceHref: '/services/bpo',
    relatedServiceName: 'BPO',
    keywords: 'BPO vs internal team, outsourcing vs in-house team, business process outsourcing comparison, when to outsource vs hire in-house',
  },
  {
    slug: 'rpo-vs-recruitment-agency',
    title: 'RPO vs. Recruitment Agency',
    subtitle: 'Both help you hire. They are built for different volumes, timelines, and levels of process ownership.',
    optionA: {
      name: 'RPO (Recruitment Process Outsourcing)',
      summary: 'An embedded, ongoing extension of your hiring function. TrivianEdge runs sourcing, screening, interview coordination, and onboarding as a continuous process, not a one-off search.',
      goodFor: ['Recurring or volume hiring across multiple roles', 'Companies that want a consistent, repeatable hiring process rather than a new agency search each time', 'Hiring across multiple countries without building local recruiting infrastructure'],
      tradeoffs: ['Best suited to ongoing hiring need, not a single urgent one-off role'],
    },
    optionB: {
      name: 'Traditional recruitment agency',
      summary: 'A transactional, per-search engagement: the agency finds and presents candidates for a specific open role, usually for a contingency or retained fee.',
      goodFor: ['A single urgent role with no ongoing hiring pipeline behind it', 'Highly specialized executive searches where a boutique agency has a specific network'],
      tradeoffs: ['Each new role typically restarts the search and fee cycle', 'Little continuity in process, employer branding, or candidate experience between searches', 'Agencies are usually not built to run interview logistics, offer management, or onboarding for you'],
    },
    rows: [
      { factor: 'Engagement model', a: 'Embedded, ongoing: runs as part of your team', b: 'Transactional: a new engagement per role or search' },
      { factor: 'Process ownership', a: 'TrivianEdge runs sourcing, screening, interview coordination, and onboarding logistics', b: 'Agency sources candidates; you still run your own interview and offer process' },
      { factor: 'Built for volume', a: 'Yes: active sourcing across six countries, four-stage screening at scale', b: 'Typically optimized for one role at a time' },
      { factor: 'Consistency across roles', a: 'One process, one point of contact, consistent candidate experience', b: 'Varies by agency and by search' },
      { factor: 'Best fit', a: 'Recurring or multi-role hiring, or hiring across new countries', b: 'A single hard-to-fill or executive role' },
    ],
    verdict: 'If you\'re hiring one role and need it filled fast, a good agency can work well. If you\'re hiring repeatedly (building out a team, entering a new market, or replacing agency spend that\'s scaling with headcount), RPO is built for that volume and gives you one consistent process instead of restarting with a new agency every time.',
    faqs: [
      { question: 'Is RPO more expensive than an agency?', answer: 'It depends on volume. Agencies typically charge per placement, which can add up fast at volume; RPO is scoped for ongoing hiring, so the per-hire cost usually comes down the more you hire. Contact us for a custom quote based on your volume and role mix.' },
      { question: 'Can RPO handle a single urgent role too?', answer: 'Yes: TrivianEdge offers both full-cycle embedded RPO and project-based engagements for a specific hiring push, so a single urgent need doesn\'t require committing to an ongoing retainer.' },
      { question: 'Does RPO include a replacement guarantee like some agencies offer?', answer: 'Yes. TrivianEdge offers a replacement guarantee for every placement: if a hire leaves or underperforms within the agreed warranty period, we re-run the search at no additional cost. Exact terms are agreed upon upfront.' },
    ],
    relatedServiceHref: '/services/rpo',
    relatedServiceName: 'RPO',
    keywords: 'RPO vs recruitment agency, recruitment process outsourcing comparison, RPO vs staffing agency, embedded recruiting vs agency hiring',
  },
  {
    slug: 'eor-vs-foreign-entity',
    title: 'Employer-of-Record Partners vs. Setting Up a Foreign Entity',
    subtitle: 'Both let you legally employ people in another country. They differ enormously in setup time, cost, and how much ongoing legal overhead you carry.',
    optionA: {
      name: 'EOR / payroll partner model',
      summary: 'TrivianEdge coordinates your employment relationship through in-country employer-of-record and payroll partners, so you never register a local company yourself.',
      goodFor: ['Testing a new market or hiring a small team before committing to a full local presence', 'Getting hires legally employed in days or weeks, not months', 'Avoiding the ongoing legal, tax, and compliance overhead of owning a foreign subsidiary'],
      tradeoffs: ['Not the right structure if you plan a large, permanent local operation with its own legal identity in that country'],
    },
    optionB: {
      name: 'Setting up your own foreign entity',
      summary: 'You register a local subsidiary or branch, becoming the direct legal employer with full control over local structure, banking, and benefits design.',
      goodFor: ['Large, long-term operations where the local entity itself is strategically valuable', 'Companies that need full control over local benefits, equity plans, or banking relationships'],
      tradeoffs: ['Registration alone can take months and requires local legal and accounting counsel', 'You carry ongoing statutory filings, local tax compliance, and employment law risk directly'],
    },
    rows: [
      { factor: 'Setup time', a: 'Days to weeks', b: 'Often months, depending on jurisdiction' },
      { factor: 'Upfront cost', a: 'No entity registration or local legal setup cost', b: 'Legal, accounting, and registration fees before you hire anyone' },
      { factor: 'Who carries compliance risk', a: 'The EOR/payroll partner administers local law; TrivianEdge manages that relationship', b: 'You, directly, as the registered legal employer' },
      { factor: 'Ongoing overhead', a: 'Bundled into one relationship with TrivianEdge', b: 'Local accounting, statutory filings, and legal counsel on retainer' },
      { factor: 'Best fit', a: 'Testing a market, or teams from a handful of people up to mid-size', b: 'Large, permanent operations where the local entity has its own strategic value' },
    ],
    verdict: 'For most companies hiring their first offshore team members, an EOR/partner model gets you legally compliant and hiring in weeks instead of months, without the fixed cost of a foreign subsidiary. It becomes worth setting up your own entity once the local team is large and permanent enough that owning the legal structure outright pays for itself.',
    faqs: [
      { question: 'Do I need a foreign entity to work with TrivianEdge?', answer: 'No. TrivianEdge coordinates employment through in-country employer-of-record and payroll partners specifically so you don\'t need to set up a foreign entity, payroll account, or legal structure yourself.' },
      { question: 'What happens if I outgrow the EOR model?', answer: 'Some clients do eventually set up their own entity once a local team is large enough to justify it. We can advise on that transition based on what we\'ve seen work, though the legal setup itself is handled by your own counsel in that jurisdiction.' },
      { question: 'Is this the same as what a PEO does domestically?', answer: 'Conceptually similar: a domestic PEO co-employs staff in your home country; an EOR/payroll partner does the equivalent for employment in a foreign jurisdiction.' },
    ],
    relatedServiceHref: '/services/bpo',
    relatedServiceName: 'BPO',
    keywords: 'EOR vs foreign entity, employer of record vs local entity, EOR vs subsidiary setup, international employment comparison',
  },
  {
    slug: 'ai-development-agency-vs-in-house-team',
    title: 'AI Development Agency vs. Building an In-House AI Team',
    subtitle: 'Both can ship AI features. The right call depends on how urgent the timeline is, how specialized the work is, and whether AI is a core, ongoing capability or a defined project.',
    optionA: {
      name: 'TrivianEdge AI Development',
      summary: 'An offshore AI engineering team (generative AI, LLM integration, ML, and MLOps specialists) deployed to your project without a multi-month hiring cycle.',
      goodFor: [
        'Shipping a defined AI feature or product without spending months hiring specialized ML/AI talent',
        'Accessing skills that are scarce or expensive locally: LLM integration, MLOps, applied ML',
        'Testing whether an AI initiative is worth a permanent in-house investment before committing to one',
      ],
      tradeoffs: [
        'Deep, long-term institutional AI capability still benefits from a core in-house team eventually',
        'Works best with a defined scope or roadmap, not fully open-ended exploratory research',
      ],
    },
    optionB: {
      name: 'In-house AI team',
      summary: 'You hire ML engineers, AI researchers, and MLOps specialists directly: full control and long-term institutional knowledge, but a slow, expensive, and competitive hiring process.',
      goodFor: [
        'Companies where AI is the core product and needs permanent, deeply embedded ownership',
        'Organizations with the budget and pipeline to compete for scarce senior AI talent',
      ],
      tradeoffs: [
        'AI/ML specialists are some of the most competitive and expensive roles to hire for',
        'Building a team from zero typically takes months before the first feature ships',
      ],
    },
    rows: [
      { factor: 'Time to first shipped feature', a: 'Team deployed in around 30 days', b: 'Often 3-6+ months once sourcing, interviewing, and onboarding senior AI talent is accounted for' },
      { factor: 'Access to specialized skills', a: 'LLM integration, RAG, MLOps, and applied ML specialists available immediately', b: 'Limited by local talent pool and your ability to compete for scarce, high-demand roles' },
      { factor: 'Cost structure', a: 'One scoped engagement covering the team and delivery', b: 'Senior AI/ML salaries plus full employer overhead and recruiting cost' },
      { factor: 'Flexibility', a: 'Scale the team up or down as the roadmap changes', b: 'Headcount changes mean hiring or layoffs' },
      { factor: 'Best fit', a: 'Defined AI features, products, or a specific technical gap (e.g. LLM integration, MLOps)', b: 'AI as a permanent, core, and continuously evolving product capability' },
    ],
    verdict: 'If you need to ship a specific AI capability (a chatbot, a RAG system, a fine-tuned model integration) without spending a quarter hiring for it, an AI development agency gets you there faster and without the hiring risk. If AI is your core, ongoing product differentiator, an in-house team eventually earns its cost. Many TrivianEdge clients start with an offshore AI team to validate the initiative, then decide whether to bring it in-house.',
    faqs: [
      { question: 'Can TrivianEdge work alongside our existing engineering team?', answer: 'Yes. Our AI development team commonly integrates with an existing product/engineering team, handling the AI-specific workstream (LLM integration, RAG, ML models, or MLOps) while your team owns the core product.' },
      { question: 'What if we want to eventually bring AI development in-house?', answer: 'That is a common path. We build with clean handoffs and documentation in mind, so a client can transition ownership to an in-house team once it is proven out and the roadmap justifies the permanent hire.' },
      { question: 'What AI development work is a good first engagement?', answer: 'A defined, scoped feature (an AI chatbot, a RAG-based knowledge assistant, or an LLM integration into an existing product) is typically the fastest way to prove value before expanding scope.' },
    ],
    relatedServiceHref: '/services/ai-development',
    relatedServiceName: 'AI Development',
    keywords: 'AI development agency vs in-house team, outsource AI development, hire AI development agency, in-house AI team cost, AI development outsourcing comparison',
  },
  {
    slug: 'bespoke-software-vs-freelance-platforms',
    title: 'Bespoke Software Development vs. Freelance Platforms',
    subtitle: 'Both can get code written. They differ sharply in continuity, accountability, and how well the result holds up as your product grows.',
    optionA: {
      name: 'TrivianEdge Bespoke Software Development',
      summary: 'A dedicated offshore engineering team, managed and consistent, building your product with full code ownership on your side from day one.',
      goodFor: [
        'Products that need a consistent team across sprints, not a new contractor each time',
        'Work that requires ongoing maintenance, iteration, and institutional context, not a one-off deliverable',
        'Teams that want a single accountable partner for delivery, not a marketplace of independent contractors',
      ],
      tradeoffs: [
        'Requires a defined engagement rather than a single small task posted for bids',
      ],
    },
    optionB: {
      name: 'Freelance platforms',
      summary: 'You post a task or project and hire independent freelancers per job, typically without continuity between engagements.',
      goodFor: [
        'Small, well-defined, one-off tasks with no ongoing maintenance need',
        'Quick, low-stakes work where switching freelancers between tasks is not a problem',
      ],
      tradeoffs: [
        'Little continuity: a new freelancer often means relearning your codebase from scratch',
        'Quality and reliability vary significantly and are hard to vet in advance',
        'No single accountable point of contact if something goes wrong post-delivery',
      ],
    },
    rows: [
      { factor: 'Continuity', a: 'Same dedicated team across the project lifecycle', b: 'Often a different freelancer per task, with re-onboarding each time' },
      { factor: 'Accountability', a: 'One partner accountable for delivery, quality, and code ownership', b: 'Individual freelancer accountability, with no larger organization backing the work' },
      { factor: 'Code ownership', a: 'Full code ownership transfers to you as standard practice', b: 'Varies by platform and contract; often requires explicit negotiation' },
      { factor: 'Ongoing maintenance fit', a: 'Built for products that need continued iteration post-launch', b: 'Typically better suited to discrete, bounded tasks' },
      { factor: 'Best fit', a: 'A product or platform you plan to build on over time', b: 'A small, well-scoped, one-off task' },
    ],
    verdict: 'For a single small task with no future iteration, a freelance platform can be the faster, cheaper choice. For a product you intend to build on (where continuity, code quality, and a single accountable partner matter as the codebase grows), a dedicated bespoke software team avoids the re-onboarding cost and quality variance of hiring a new freelancer for every task.',
    faqs: [
      { question: 'Do we own the code TrivianEdge writes for us?', answer: 'Yes. Full code ownership is standard practice on TrivianEdge bespoke software engagements.' },
      { question: 'Can TrivianEdge take over a project that was started on a freelance platform?', answer: 'Yes: this is a common engagement. Our team can review, document, and take ownership of an existing codebase before continuing development.' },
      { question: 'Is bespoke software development more expensive than freelance platforms?', answer: 'Per-hour rates can look similar, but freelance engagements often carry hidden re-onboarding and quality-variance costs across multiple hires. A dedicated team avoids that by staying consistent across the project.' },
    ],
    relatedServiceHref: '/services/it-outsourcing',
    relatedServiceName: 'Bespoke Software Development',
    keywords: 'bespoke software development vs freelance, custom software development vs freelancers, dedicated development team vs freelance platform, offshore development team vs Upwork',
  },
];
