import { ServiceCountryCombo } from '../types';

export const SERVICE_COUNTRY_COMBOS: ServiceCountryCombo[] = [
  {
    service: 'bpo',
    serviceName: 'BPO',
    metaTitle: 'BPO Outsourcing in the Philippines | TrivianEdge',
    serviceHref: '/services/bpo',
    countrySlug: 'philippines',
    hubId: 'phl',
    angle: 'The Philippines is TrivianEdge\'s deepest BPO hub: native-level English, a mature IT-BPM ecosystem, and a workforce built around operational and customer-facing excellence. It is the hub most of our back-office, support, and finance-ops BPO placements come from.',
    typicalRoles: ['Customer support specialists', 'Back-office & data processing', 'Finance & accounting support', 'Administrative controllers', 'Documentation & compliance specialists'],
    keywords: 'BPO Philippines, offshore BPO team Philippines, business process outsourcing Philippines, customer support outsourcing Philippines, back-office outsourcing Philippines',
    faqs: [
      { question: 'Why is the Philippines TrivianEdge\'s primary BPO hub?', answer: 'Native-level English fluency, deep Western cultural alignment, and a mature IT-BPM ecosystem across Metro Manila and secondary cities make integration with North American and Australian businesses fast and low-friction.' },
      { question: 'What time zone fit does a Philippines BPO team offer?', answer: 'GMT+8: this aligns well with US night-shift coverage and Australian daytime hours, which is part of why cross-timezone BPO models (like the one built for Cargo Login) often anchor on a Philippines-based team.' },
      { question: 'What roles does TrivianEdge typically place from the Philippines?', answer: 'Customer support, back-office and data processing, finance and accounting support, and documentation-heavy operational roles: the functions where operational precision and communication quality matter most.' },
    ],
  },
  {
    service: 'rpo',
    serviceName: 'RPO',
    metaTitle: 'RPO & Hiring in the Philippines | TrivianEdge',
    serviceHref: '/services/rpo',
    countrySlug: 'philippines',
    hubId: 'phl',
    angle: 'The Philippines\' deep IT-BPM talent pool makes it a strong RPO hub for operational and customer-facing roles at volume: support, back-office, and finance-ops hires sourced and screened at scale.',
    typicalRoles: ['Customer support leads', 'Finance & accounting hires', 'Back-office operations staff', 'Administrative coordinators', 'QA & process specialists'],
    keywords: 'RPO Philippines, recruitment outsourcing Philippines, hire operations staff Philippines, offshore recruitment Philippines',
    faqs: [
      { question: 'Why hire through RPO in the Philippines rather than BPO?', answer: 'RPO places direct hires onto your own team, so you own day-to-day management once they\'re hired. It\'s a fit when you want a Philippines-based operational hire to be functionally part of your team, not a managed outsourced function.' },
      { question: 'What roles does TrivianEdge source through RPO in the Philippines?', answer: 'Primarily operational and customer-facing hires: customer support leads, finance and accounting staff, back-office coordinators, roles that benefit from the Philippines\' deep service-industry talent pool.' },
      { question: 'What is the time zone overlap for a Philippines-based hire?', answer: 'GMT+8: strong alignment with US night-shift coverage and Australian daytime hours.' },
    ],
  },
  {
    service: 'it-outsourcing',
    serviceName: 'IT Outsourcing',
    metaTitle: 'Offshore Software Development in the Philippines | TrivianEdge',
    serviceHref: '/services/it-outsourcing',
    countrySlug: 'philippines',
    hubId: 'phl',
    angle: 'The Philippines suits Canadian companies that want offshore developers who integrate quickly with North American teams: native-level English, deep Western business alignment, and a mature IT-BPM ecosystem across Manila, Cebu City, and Davao. TrivianEdge contracts from Toronto and places dedicated Philippines-based engineers for web platforms, business systems, and the support engineering around them.',
    typicalRoles: ['PHP / Laravel developers', 'Python developers', 'Salesforce developers & admins', 'NetSuite developers & consultants', 'QA & technical support engineers'],
    keywords: 'offshore software development Philippines, offshore software development Canada Philippines, hire Filipino developers Canada, IT outsourcing Philippines, offshore developers Philippines',
    faqs: [
      { question: 'Why do Canadian companies outsource software development to the Philippines?', answer: 'Native-level English and strong Western cultural alignment keep communication overhead low, and the Philippines\' mature IT-BPM ecosystem supplies experienced engineers for web platforms and business systems. TrivianEdge adds a Toronto-based contract and client management, so you deal with a Canadian company throughout.' },
      { question: 'What kind of development work fits a Philippines-based team?', answer: 'Web platforms (PHP/Laravel, Python), CRM and ERP work on Salesforce and NetSuite, QA, and the technical support engineering that keeps those systems running, especially where the team works closely with your customer-facing or operations staff.' },
      { question: 'What is the time zone overlap between the Philippines and Canada?', answer: 'The Philippines is on GMT+8, so a Philippines team works during North American evenings and overnight. That suits follow-the-sun coverage, overnight QA and support, and async handoffs; for real-time collaboration, teams schedule a daily overlap window.' },
    ],
  },
  {
    service: 'rpo',
    serviceName: 'RPO',
    metaTitle: 'RPO & Software Engineer Hiring in Sri Lanka | TrivianEdge',
    serviceHref: '/services/rpo',
    countrySlug: 'sri-lanka',
    hubId: 'lka',
    angle: 'Sri Lanka is TrivianEdge\'s software engineering talent hub: boutique engineering depth and strong problem-solving for complex, enterprise-grade systems. RPO placements from Sri Lanka skew toward technical and engineering roles rather than volume operational hiring.',
    typicalRoles: ['Full-stack & backend engineers', 'Data engineers & architects', '.NET / Java engineers', 'Cloud & DevOps specialists', 'QA engineers'],
    keywords: 'RPO Sri Lanka, hire software engineers Sri Lanka, engineering recruitment Sri Lanka, offshore developer hiring Sri Lanka',
    faqs: [
      { question: 'Why hire engineers through RPO in Sri Lanka?', answer: 'Sri Lanka has a resilient talent base known for boutique software engineering and complex data architecture, with exceptional English proficiency and a culture of transparent, collaborative project management: good fit for embedded technical hiring, not just staffing.' },
      { question: 'How does RPO in Sri Lanka differ from BPO in the Philippines?', answer: 'RPO places direct hires onto your own team: you own the employment relationship\'s day-to-day management once they\'re hired, coordinated through in-country EOR partners. It\'s a fit when you want engineers who are functionally part of your team, not an outsourced function.' },
      { question: 'What is the time zone overlap for a Sri Lanka-based engineering hire?', answer: 'GMT+5:30: partial overlap with European and Asia-Pacific working hours, which most engineering teams manage well with a few hours of daily overlap plus async workflows.' },
    ],
  },
  {
    service: 'ai-development',
    serviceName: 'AI Development',
    metaTitle: 'AI Development Team in Sri Lanka | TrivianEdge',
    serviceHref: '/services/ai-development',
    countrySlug: 'sri-lanka',
    hubId: 'lka',
    angle: 'Sri Lanka\'s software engineering depth extends naturally into applied AI: data architecture and backend engineering strength that supports complex ML pipelines, LLM integrations, and production AI systems.',
    typicalRoles: ['ML & data engineers', 'LLM integration engineers', 'Backend engineers for AI systems', 'Data architects', 'QA engineers for AI/ML products'],
    keywords: 'AI development Sri Lanka, hire AI engineers Sri Lanka, machine learning team Sri Lanka, offshore AI development Sri Lanka',
    faqs: [
      { question: 'Why build AI systems with a Sri Lanka-based team?', answer: 'Sri Lanka\'s engineering talent is known for strong data architecture and complex-systems problem-solving: the same skills that underpin reliable ML pipelines and production LLM integrations.' },
      { question: 'What AI development work does TrivianEdge staff from Sri Lanka?', answer: 'Machine learning and data engineering, LLM integration, and the backend engineering that supports AI features in production, typically for enterprise-grade systems.' },
      { question: 'What is the time zone alignment for a Sri Lanka AI team?', answer: 'GMT+5:30: workable overlap with European and Asia-Pacific teams, managed well with async workflows.' },
    ],
  },
  {
    service: 'it-outsourcing',
    serviceName: 'IT Outsourcing',
    metaTitle: 'Bespoke Software Development in Sri Lanka | TrivianEdge',
    serviceHref: '/services/it-outsourcing',
    countrySlug: 'sri-lanka',
    hubId: 'lka',
    angle: 'Sri Lanka is TrivianEdge\'s core software engineering hub: dedicated teams for custom application development, cloud/DevOps, and enterprise-grade systems, backed by modern tech-park infrastructure and 24/7 connectivity.',
    typicalRoles: ['Full-stack engineers', 'Cloud & DevOps engineers', '.NET / Java engineers', 'QA engineers', 'Technical project leads'],
    keywords: 'bespoke software development Sri Lanka, offshore software development Sri Lanka, custom development team Sri Lanka, IT outsourcing Sri Lanka',
    faqs: [
      { question: 'Why choose Sri Lanka for bespoke software development?', answer: 'A mature engineering talent base with strength in complex, enterprise-grade systems, exceptional English proficiency, and modern tech-park infrastructure with reliable 24/7 connectivity.' },
      { question: 'What kind of software projects fit a Sri Lanka team best?', answer: 'Custom applications and platforms that benefit from deep engineering and data-architecture skill: enterprise systems, complex integrations, and long-term product builds.' },
      { question: 'What is the time zone overlap for a Sri Lanka development team?', answer: 'GMT+5:30: partial overlap with EU/Asia/Australia hours, typically managed with a few hours of daily sync plus async workflows.' },
    ],
  },
  {
    service: 'ai-development',
    serviceName: 'AI Development',
    serviceHref: '/services/ai-development',
    countrySlug: 'vietnam',
    hubId: 'vnm',
    angle: 'Vietnam is TrivianEdge\'s fastest-growing tech hub: a large, tech-savvy young talent pool with heavy government investment in digital infrastructure and STEM education, and strong adoption of modern AI/ML tooling and Agile practices.',
    typicalRoles: ['AI & machine learning engineers', 'LLM integration engineers', 'Backend engineers (Node.js, Golang, Python)', 'Data scientists', 'MLOps engineers'],
    keywords: 'AI development Vietnam, hire AI engineers Vietnam, LLM integration Vietnam, offshore AI team Vietnam, machine learning outsourcing Vietnam',
    faqs: [
      { question: 'Why build AI products with a Vietnam-based team?', answer: 'Vietnam combines rapid development cycles with a workforce that\'s highly adaptive to modern Agile and DevOps frameworks, backed by aggressive government investment in STEM education and digital infrastructure: a strong fit for fast-moving AI feature work.' },
      { question: 'What AI development work does TrivianEdge typically staff from Vietnam?', answer: 'LLM integration, RAG systems, and AI feature engineering are common: teams built on current OpenAI, Anthropic, and open-weight models, plus the data and MLOps engineering to support them in production.' },
      { question: 'What is the time zone alignment with Vietnam?', answer: 'GMT+7: strong APAC alignment, and workable overlap windows for North American and European teams that build async-friendly workflows around it.' },
    ],
  },
  {
    service: 'it-outsourcing',
    serviceName: 'IT Outsourcing',
    metaTitle: 'Bespoke Software Development in Vietnam | TrivianEdge',
    serviceHref: '/services/it-outsourcing',
    countrySlug: 'vietnam',
    hubId: 'vnm',
    angle: 'Vietnam pairs a large, fast-growing tech talent pool with strong Agile and DevOps adoption, making it a reliable hub for custom application development at speed and scale.',
    typicalRoles: ['Full-stack engineers (Node.js, Golang, Python)', 'Cloud & DevOps engineers', 'QA engineers', 'Mobile developers', 'Technical project leads'],
    keywords: 'bespoke software development Vietnam, offshore software development Vietnam, custom development team Vietnam, IT outsourcing Vietnam',
    faqs: [
      { question: 'Why choose Vietnam for bespoke software development?', answer: 'A large, tech-savvy talent pool, heavy government investment in digital infrastructure and STEM education, and strong adoption of modern Agile and DevOps practices support fast-moving development cycles.' },
      { question: 'What kind of projects fit a Vietnam-based team best?', answer: 'Custom applications, mobile products, and platforms where development speed and modern tooling adoption matter: Vietnam\'s teams are built around fast iteration.' },
      { question: 'What is the time zone alignment with Vietnam?', answer: 'GMT+7: strong APAC alignment, workable for North American and European teams using async-friendly workflows.' },
    ],
  },
  {
    service: 'rpo',
    serviceName: 'RPO',
    metaTitle: 'RPO & Engineering Hiring in Vietnam | TrivianEdge',
    serviceHref: '/services/rpo',
    countrySlug: 'vietnam',
    hubId: 'vnm',
    angle: 'Vietnam\'s fast-growing tech talent pool makes it a strong RPO hub for direct engineering and AI hires, particularly where a client wants a Vietnam-based engineer functionally embedded on their own team.',
    typicalRoles: ['Software engineers', 'AI/ML engineers', 'Mobile developers', 'QA engineers', 'DevOps engineers'],
    keywords: 'RPO Vietnam, hire engineers Vietnam, tech recruitment Vietnam, offshore developer hiring Vietnam',
    faqs: [
      { question: 'Why hire engineers through RPO in Vietnam?', answer: 'Vietnam\'s large, fast-growing tech talent pool and strong modern-tooling adoption make it a reliable source for direct technical hires, not just staffed teams.' },
      { question: 'How does RPO in Vietnam differ from AI development staffing there?', answer: 'RPO places a direct hire onto your own team, which you manage day-to-day; our AI development service instead delivers a managed, outcome-owned engineering team. Which fits depends on whether you want a hire or a delivered project.' },
      { question: 'What is the time zone overlap for a Vietnam-based hire?', answer: 'GMT+7: strong APAC alignment, workable for North American and European teams with async-friendly workflows.' },
    ],
  },
  {
    service: 'it-outsourcing',
    serviceName: 'IT Outsourcing',
    serviceHref: '/services/it-outsourcing',
    countrySlug: 'costa-rica',
    hubId: 'cri',
    angle: 'Costa Rica is the premier nearshore option for North American IT outsourcing: bilingual talent, US-aligned time zones, and a stable, business-friendly environment that makes real-time collaboration with US and Canadian teams straightforward.',
    typicalRoles: ['Full-stack engineers (React, Node.js, Ruby on Rails)', 'DevOps & cloud engineers', 'QA engineers', 'Cybersecurity specialists', 'Technical project managers'],
    keywords: 'IT outsourcing Costa Rica, nearshore software development Costa Rica, bespoke software development Costa Rica, offshore development team Costa Rica',
    faqs: [
      { question: 'Why choose Costa Rica for nearshore IT outsourcing?', answer: 'Costa Rica offers US Central/Eastern-aligned time zones (GMT-6), fluent bilingual talent, and a politically stable, business-friendly environment: ideal when your team needs real-time overlap with US or Canadian working hours rather than an overnight handoff model.' },
      { question: 'How is nearshore different from TrivianEdge\'s other offshore hubs?', answer: 'Nearshore hubs like Costa Rica prioritize timezone overlap for real-time collaboration, while hubs like the Philippines or Sri Lanka are often chosen for cost efficiency or specific technical depth even with less daily overlap. We help you match the hub to how your team actually needs to work.' },
      { question: 'What kind of engineering work fits a Costa Rica team best?', answer: 'Work that benefits from daily real-time collaboration with a North American product or engineering team: full-stack development, DevOps, and QA where fast, synchronous back-and-forth speeds up delivery.' },
    ],
  },
  {
    service: 'ai-development',
    serviceName: 'AI Development',
    metaTitle: 'AI Development Team in Costa Rica | TrivianEdge',
    serviceHref: '/services/ai-development',
    countrySlug: 'costa-rica',
    hubId: 'cri',
    angle: 'Costa Rica pairs nearshore time-zone overlap with bilingual technical talent: a fit for AI development work that benefits from daily, real-time collaboration with a North American product team.',
    typicalRoles: ['AI/ML engineers', 'LLM integration engineers', 'Full-stack engineers for AI products', 'QA engineers', 'Technical project managers'],
    keywords: 'AI development Costa Rica, nearshore AI development, hire AI engineers Costa Rica, offshore AI team Costa Rica',
    faqs: [
      { question: 'Why choose Costa Rica for AI development?', answer: 'Real-time overlap with US Central/Eastern hours makes fast, synchronous iteration possible: useful for AI features that need close, daily collaboration with your product team rather than an overnight handoff model.' },
      { question: 'Is Costa Rica a fit for early-stage AI experimentation?', answer: 'Yes: the real-time overlap supports the fast feedback loops that early-stage AI feature work often needs, compared to hubs better suited to more asynchronous, spec-driven work.' },
      { question: 'What is the time zone alignment with Costa Rica?', answer: 'GMT-6, aligned with US Central and workable with Eastern time zones: same-day overlap for most of a North American workday.' },
    ],
  },
  {
    service: 'rpo',
    serviceName: 'RPO',
    metaTitle: 'RPO & Engineering Hiring in Costa Rica | TrivianEdge',
    serviceHref: '/services/rpo',
    countrySlug: 'costa-rica',
    hubId: 'cri',
    angle: 'Costa Rica\'s bilingual, US-timezone-aligned engineering talent makes it a strong RPO hub for direct technical hires who need to work in real time with a North American team.',
    typicalRoles: ['Full-stack engineers', 'DevOps engineers', 'QA engineers', 'Cybersecurity specialists', 'Technical project managers'],
    keywords: 'RPO Costa Rica, hire engineers Costa Rica, nearshore recruitment Costa Rica, offshore developer hiring Costa Rica',
    faqs: [
      { question: 'Why hire engineers through RPO in Costa Rica?', answer: 'Bilingual talent and US-aligned time zones mean a Costa Rica-based hire can work in real time with your existing team from day one, without an overnight handoff model.' },
      { question: 'How does RPO in Costa Rica differ from IT outsourcing there?', answer: 'RPO places a direct hire onto your own team, which you manage day-to-day; IT outsourcing instead delivers a managed engineering team and outcome. Which fits depends on whether you want a hire or a delivered project.' },
      { question: 'What is the time zone overlap for a Costa Rica-based hire?', answer: 'GMT-6: aligned with US Central and workable with Eastern time zones, giving same-day overlap for most of a North American workday.' },
    ],
  },
  {
    service: 'bpo',
    serviceName: 'BPO',
    metaTitle: 'BPO Outsourcing in Turkey | TrivianEdge',
    serviceHref: '/services/bpo',
    countrySlug: 'turkey',
    hubId: 'tur',
    angle: 'Turkey\'s strategic position as a bridge between Europe and Asia, combined with strong EU/UK time-zone alignment, makes it a strong BPO hub for operations that need to run in step with European business hours.',
    typicalRoles: ['Customer support specialists', 'Back-office operations', 'Multilingual support agents', 'Administrative coordinators', 'Documentation specialists'],
    keywords: 'BPO Turkey, business process outsourcing Turkey, offshore back-office team Turkey, customer support outsourcing Turkey',
    faqs: [
      { question: 'Why choose Turkey for BPO?', answer: 'Turkey\'s GMT+3 time zone gives near-perfect alignment with EU and UK business hours, combined with a workforce built around strategic bridge operations between European and Asian markets.' },
      { question: 'What roles does TrivianEdge typically place from Turkey?', answer: 'Customer support, back-office operations, and administrative coordination roles, particularly where EU/UK business-hours alignment matters.' },
      { question: 'What is the time zone alignment with Turkey?', answer: 'GMT+3: near-perfect overlap with EU and UK working hours.' },
    ],
  },
  {
    service: 'it-outsourcing',
    serviceName: 'IT Outsourcing',
    metaTitle: 'Bespoke Software Development in Turkey | TrivianEdge',
    serviceHref: '/services/it-outsourcing',
    countrySlug: 'turkey',
    hubId: 'tur',
    angle: 'Turkey\'s strategic bridge-ops-and-tech talent base, combined with near-perfect EU/UK time-zone alignment, supports custom software delivery for European-facing teams that need daily real-time collaboration.',
    typicalRoles: ['Full-stack engineers', 'Cloud & DevOps engineers', 'QA engineers', 'Systems integration specialists', 'Technical project managers'],
    keywords: 'bespoke software development Turkey, offshore software development Turkey, IT outsourcing Turkey, custom development team Turkey',
    faqs: [
      { question: 'Why choose Turkey for bespoke software development?', answer: 'Near-perfect EU/UK time-zone alignment (GMT+3) supports daily real-time collaboration, backed by a talent base built around strategic bridge operations and technology.' },
      { question: 'What kind of software projects fit a Turkey-based team best?', answer: 'Projects for European-facing businesses that need close, synchronous collaboration during EU/UK working hours.' },
      { question: 'What is the time zone alignment with Turkey?', answer: 'GMT+3: near-perfect overlap with EU and UK working hours.' },
    ],
  },
  {
    service: 'bpo',
    serviceName: 'BPO',
    metaTitle: 'BPO Outsourcing in South Africa | TrivianEdge',
    serviceHref: '/services/bpo',
    countrySlug: 'south-africa',
    hubId: 'zaf',
    angle: 'South Africa\'s specialized financial and operations talent base, combined with strong UK/EU time-zone alignment, makes it a strong BPO hub for finance-ops and specialized back-office functions.',
    typicalRoles: ['Finance & accounting support', 'Specialized operations analysts', 'Customer support specialists', 'Back-office & data processing', 'Administrative controllers'],
    keywords: 'BPO South Africa, business process outsourcing South Africa, offshore finance operations South Africa, back-office outsourcing South Africa',
    faqs: [
      { question: 'Why choose South Africa for BPO?', answer: 'South Africa\'s talent base is known for financial and specialized operations work, combined with GMT+2 alignment to UK and EU business hours.' },
      { question: 'What roles does TrivianEdge typically place from South Africa?', answer: 'Finance and accounting support, specialized operations analysis, and back-office functions where financial-domain expertise matters.' },
      { question: 'What is the time zone alignment with South Africa?', answer: 'GMT+2: strong alignment with UK and EU working hours.' },
    ],
  },
  {
    service: 'rpo',
    serviceName: 'RPO',
    metaTitle: 'RPO & Finance Hiring in South Africa | TrivianEdge',
    serviceHref: '/services/rpo',
    countrySlug: 'south-africa',
    hubId: 'zaf',
    angle: 'South Africa\'s depth in financial and specialized operations talent makes it a strong RPO hub for direct finance, ops, and analyst hires that need to sit on your own team.',
    typicalRoles: ['Finance & accounting hires', 'Operations analysts', 'Compliance specialists', 'Administrative coordinators', 'Customer support leads'],
    keywords: 'RPO South Africa, hire finance staff South Africa, recruitment outsourcing South Africa, offshore hiring South Africa',
    faqs: [
      { question: 'Why hire through RPO in South Africa?', answer: 'South Africa\'s financial and specialized-operations talent base is a strong fit for direct hires in finance, ops, and compliance-adjacent roles.' },
      { question: 'How does RPO in South Africa differ from BPO there?', answer: 'RPO places a direct hire onto your own team, which you manage day-to-day; BPO instead delivers a managed, outsourced function. Which fits depends on whether you want a hire or a delivered outcome.' },
      { question: 'What is the time zone overlap for a South Africa-based hire?', answer: 'GMT+2: strong alignment with UK and EU working hours.' },
    ],
  },
];
